# Size and steps
size: 20
max_steps: 500

# Rendering
render_mode: rgb_array
show_fov_display: False

# Rewards
intrinsic: False
lambda_fov: 0.5
show_target_coords: False
obstacle_collision_penalty: -0.05

# Targets and agents
no_target: False
agents: None
target_config: None
death_on_sight: True

# Obstacles
enable_obstacles: True
num_obstacles: 5
num_visual_obstacles: 5